/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedClassCriteriaRouteImport } from './routes/_authenticated/class-criteria'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEduqorRouteImport } from './routes/_authenticated/eduqor'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedPasswordRouteImport } from './routes/_authenticated/password'
import { Route as AuthenticatedRatingRouteImport } from './routes/_authenticated/rating'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicSeedRosterRouteImport } from './routes/api/public/seed-roster'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassCriteriaRoute =
  AuthenticatedClassCriteriaRouteImport.update({
    id: '/class-criteria',
    path: '/class-criteria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEduqorRoute = AuthenticatedEduqorRouteImport.update({
  id: '/eduqor',
  path: '/eduqor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPasswordRoute = AuthenticatedPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRatingRoute = AuthenticatedRatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedRosterRoute = ApiPublicSeedRosterRouteImport.update({
  id: '/api/public/seed-roster',
  path: '/api/public/seed-roster',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/class-criteria': typeof AuthenticatedClassCriteriaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eduqor': typeof AuthenticatedEduqorRoute
  '/events': typeof AuthenticatedEventsRoute
  '/password': typeof AuthenticatedPasswordRoute
  '/rating': typeof AuthenticatedRatingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/seed-roster': typeof ApiPublicSeedRosterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/class-criteria': typeof AuthenticatedClassCriteriaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eduqor': typeof AuthenticatedEduqorRoute
  '/events': typeof AuthenticatedEventsRoute
  '/password': typeof AuthenticatedPasswordRoute
  '/rating': typeof AuthenticatedRatingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/seed-roster': typeof ApiPublicSeedRosterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/class-criteria': typeof AuthenticatedClassCriteriaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/eduqor': typeof AuthenticatedEduqorRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/password': typeof AuthenticatedPasswordRoute
  '/_authenticated/rating': typeof AuthenticatedRatingRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/seed-roster': typeof ApiPublicSeedRosterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/assistant'
    | '/attendance'
    | '/class-criteria'
    | '/dashboard'
    | '/eduqor'
    | '/events'
    | '/password'
    | '/rating'
    | '/reports'
    | '/api/chat'
    | '/api/public/seed-roster'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/assistant'
    | '/attendance'
    | '/class-criteria'
    | '/dashboard'
    | '/eduqor'
    | '/events'
    | '/password'
    | '/rating'
    | '/reports'
    | '/api/chat'
    | '/api/public/seed-roster'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/assistant'
    | '/_authenticated/attendance'
    | '/_authenticated/class-criteria'
    | '/_authenticated/dashboard'
    | '/_authenticated/eduqor'
    | '/_authenticated/events'
    | '/_authenticated/password'
    | '/_authenticated/rating'
    | '/_authenticated/reports'
    | '/api/chat'
    | '/api/public/seed-roster'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicSeedRosterRoute: typeof ApiPublicSeedRosterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/class-criteria': {
      id: '/_authenticated/class-criteria'
      path: '/class-criteria'
      fullPath: '/class-criteria'
      preLoaderRoute: typeof AuthenticatedClassCriteriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eduqor': {
      id: '/_authenticated/eduqor'
      path: '/eduqor'
      fullPath: '/eduqor'
      preLoaderRoute: typeof AuthenticatedEduqorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/password': {
      id: '/_authenticated/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof AuthenticatedPasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rating': {
      id: '/_authenticated/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof AuthenticatedRatingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-roster': {
      id: '/api/public/seed-roster'
      path: '/api/public/seed-roster'
      fullPath: '/api/public/seed-roster'
      preLoaderRoute: typeof ApiPublicSeedRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedClassCriteriaRoute: typeof AuthenticatedClassCriteriaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEduqorRoute: typeof AuthenticatedEduqorRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedPasswordRoute: typeof AuthenticatedPasswordRoute
  AuthenticatedRatingRoute: typeof AuthenticatedRatingRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedClassCriteriaRoute: AuthenticatedClassCriteriaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEduqorRoute: AuthenticatedEduqorRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedPasswordRoute: AuthenticatedPasswordRoute,
  AuthenticatedRatingRoute: AuthenticatedRatingRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicSeedRosterRoute: ApiPublicSeedRosterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
